arm_id: $(arg arm_id)
position_joint_position_controller:
    type: franka_ros_controllers/PositionJointPositionController
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7

velocity_joint_velocity_controller:
    type: franka_ros_controllers/VelocityJointVelocityController
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7


effort_joint_impedance_controller:
    type: franka_ros_controllers/EffortJointImpedanceController
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains: # if changing the default values, remember to change in the cfg file as well
        - 1200.0
        - 1000.0
        - 1000.0
        - 800.0
        - 300.0
        - 200.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    publish_rate: 30.0
    coriolis_factor: 1.0

effort_joint_position_controller:
    type: franka_ros_controllers/EffortJointPositionController
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 1200.0
        - 1000.0
        - 1000.0
        - 800.0
        - 300.0
        - 200.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    publish_rate: 30.0

effort_joint_torque_controller:
    type: franka_ros_controllers/EffortJointTorqueController
    compensate_coriolis: false
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7

